source $HOME\\.config\\vim\\vim-plug\\plugins.vim
source $HOME\\.config\\vim\\general\\settings.vim
source $HOME\\.config\\vim\\general\\experimental.vim
source $HOME\\.config\\vim\\keys\\mappings.vim
source $HOME\\.config\\vim\\themes\\gruvbox.vim
source $HOME\\.config\\vim\\themes\\airline.vim
source $HOME\\.config\\vim\\plug-config\\vim-startify.vim
source $HOME\\.config\\vim\\plug-config\\fzf.vim
source $HOME\\.config\\vim\\plug-config\\sneak.vim
source $HOME\\.config\\vim\\plug-config\\coc.vim
source $HOME\\.config\\vim\\plug-config\\nerdtree.vim
source $HOME\\.config\\vim\\plug-config\\vim-easyclip.vim
source $HOME\\.config\\vim\\plug-config\\emmet-config.vim
source $HOME\\.config\\vim\\plug-config\\quickscope.vim
source $HOME\\.config\\vim\\plug-config\\signify.vim
source $HOME\\.config\\vim\\plug-config\\easy-align.vim
source $HOME\\.config\\vim\\plug-config\\brightest.vim
